baseURL = "https://commander.sconeforgemystic.com/"
languageCode = "en-us"
title = "SconeforgeMystic's Commander Cube"
theme = "contrast-hugo"
enableEmoji = true

[params]
minimal = false
description = "A Magic: the Gathering Commander cube in the style of JumpStart"

[menu]
[[menu.main]]
identifier = "decks"
name = "Decks"
url = "/decks"
weight = 10